language: node_js
notifications:
  email: true
node_js: 16.15.0
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g gulp-cli
jobs:
  include:
    - stage: test
      script:
        - npm i -f
        - npm run build
