export const SET_DETAIL_TICKET_ROOM = "SET_DETAIL_TICKET_ROOM";

export const BOOKING_TICKET = "BOOKING_TICKET";

export const BOOKING_TICKETS_COMPLETE = "BOOKING_TICKETS_COMPLETE";

export const SWITCH_TAB_RESULT_BOOKING = "SWITCH_TAB_RESULT_BOOKING";

export const SWITCH_TAB_ACTIVE = "SWITCH_TAB_ACTIVE";
